apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-recommendation
  name: mongodb-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-recommendation
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-recommendation
    spec:
      containers:
        - image: mongo
          name: hotel-reserv-recommendation-mongo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 1000m
          volumeMounts:
            - mountPath: /data/db
              name: recommendation
      hostname: recommendation-db
      restartPolicy: Always
      volumes:
        - name: recommendation
          emptyDir:
            medium: Memory
status: {}
