apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: rate
  name: rate
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: rate
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: rate
    spec:
      containers:
        - command:
            - rate
          image: rajibhossen/hotel_reserv_rate_single_node
          name: hotel-reserv-rate
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          resources:
            limits:
              cpu: 1500m
      restartPolicy: Always
status: {}
